# Generated by Django 4.2.2 on 2023-06-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_remove_tasks_tag_tasks_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks_Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('task_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='tag',
        ),
    ]
