# Generated by Django 4.2.2 on 2023-06-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_alter_tasks_tags_tag_id_alter_tasks_tags_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks_tags',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tasks_tags',
            old_name='task_id',
            new_name='task',
        ),
    ]
